# user 业务 配置文件


spring:


  # 配置数据源
  datasource:

    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud_user
      username: root
      password: 20010713


  application:
    name: userservice

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10080/eureka/


  cloud:
    nacos:
      discovery:
        # nacos 服务端地址
        server-addr:  localhost:8848
        # 集群名称
        cluster-name: HZ

  #--server.port=8083
  #--spring.cloud.nacos.discovery.cluster-name=SH

# 开启debug模式，输出调试信息，常用于检查系统运行状况
#debug: true

# 设置日志级别，root表示根节点，即整体应用日志级别
logging:
  # 日志输出到文件的文件名
  file:
    name: user_server.log
  # 设置日志组
  group:
    # 自定义组名，设置当前组中所包含的包
    mao_pro: mao
  level:
    root: info
    # 为对应组设置日志级别
    mao_pro: debug
    # 日志输出格式
  # pattern:
  # console: "%d %clr(%p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"



server:
  port: 8082



mybatis:
  type-aliases-package: mao.user_service
  configuration:
    map-underscore-to-camel-case: true

